### ISSUE TITLE
[Bug]:  Cannot run webui error at start

### ISSUE THREAD

**Issue by MrSzalai** [lshqqytiger/stable-diffusion-webui-directml#213] opened 2023-07-31 19:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

i am getting module initialization error.

### Steps to reproduce the problem

idk

### What should have happened?

HELP

### Version or Commit where the problem happens

the current one

### What Python version are you running on ?

Python 3.10.x

### Cross attention optimization

None 

### Command Line Arguments

```Shell
nope
```

### List of extensions

no

### Console logs

```Shell
venv "C:\softwares\stable-diffusion-webui-directml\venv\Scripts\Python.exe"
fatal: No names found, cannot describe anything.
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: 1.5.1
Commit hash: ed20ba7f9ff593bcf012db79278930a381a55748
Launching Web UI with arguments:
no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
No module 'xformers'. Proceeding without it.
Traceback (most recent call last):
  File "C:\softwares\stable-diffusion-webui-directml\launch.py", line 39, in <module>
    main()
  File "C:\softwares\stable-diffusion-webui-directml\launch.py", line 35, in main
    start()
  File "C:\softwares\stable-diffusion-webui-directml\modules\launch_utils.py", line 443, in start
    import webui
  File "C:\softwares\stable-diffusion-webui-directml\webui.py", line 54, in <module>
    from modules.call_queue import wrap_gradio_gpu_call, wrap_queued_call, queue_lock  # noqa: F401
  File "C:\softwares\stable-diffusion-webui-directml\modules\call_queue.py", line 6, in <module>
    from modules import shared, progress, errors
  File "C:\softwares\stable-diffusion-webui-directml\modules\shared.py", line 95, in <module>
    directml_do_hijack()
  File "C:\softwares\stable-diffusion-webui-directml\modules\dml\__init__.py", line 69, in directml_do_hijack
    _set_memory_provider()
  File "C:\softwares\stable-diffusion-webui-directml\modules\dml\__init__.py", line 14, in _set_memory_provider
    from modules.shared import opts, cmd_opts, log
ImportError: cannot import name 'opts' from partially initialized module 'modules.shared' (most likely due to a circular import) (C:\softwares\stable-diffusion-webui-directml\modules\shared.py)
Press any key to continue . . .
```

**Comment by MrSzalai** [comment] 2023-07-31 19:10
So should i install an older version?

**Comment by dieselino0** [comment] 2023-07-31 19:19
I would wait at least a day until new commits are rolled out and hopefully it fixes the issue, just keep checking 
https://github.com/lshqqytiger/stable-diffusion-webui-directml/commits/master

It looks like this was added today https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/ed20ba7f9ff593bcf012db79278930a381a55748 and it broke everything

**Comment by ViralRabbit** [comment] 2023-08-01 00:19
I have the same error. Ill be watching here if anyone comes up with a fix.

**Comment by Synergyart** [comment] 2023-08-01 00:35
I had to roll back until an update hopefully fixes this bug.

**Comment by lshqqytiger** [comment] 2023-08-01 05:32
Should be fixed in 723974a8b74ffd5acc1a1fdaf36e9c2426651537

**Closed by lshqqytiger** 2023-08-01 05:32 UTC
Labels: bug, duplicate

**Comment by dieselino0** [comment] 2023-08-01 05:34
I can confirm it is fixed in https://github.com/lshqqytiger/stable-diffusion-webui-directml/commit/723974a8b74ffd5acc1a1fdaf36e9c2426651537

**Comment by MrSzalai** [comment] 2023-08-01 05:41
Nice! Thank you guys and @lshqqytiger :)
