### ISSUE TITLE
[Bug]: 7900xtx only can generate 512*512 picture

### ISSUE THREAD

**Issue by hzwyjxy** [lshqqytiger/stable-diffusion-webui-directml#7] opened 2023-02-17 04:15 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues and checked the recent builds/commits

### What happened?

7900xtx only can generate 512*512 picture,but I have 24GB vram，that's really strange

### Steps to reproduce the problem

1. Go to .... 
2. Press ....
3. ...

### What should have happened?

DirectML has bad memory control?

### Commit where the problem happens

。

### What platforms do you use to access the UI ?

Windows

### What browsers do you use to access the UI ?

Microsoft Edge

### Command Line Arguments

```Shell
I tried some command lines, but all usless
such as 
--opt-sub-quad-attention --lowvram --no-half
```

### List of extensions

。

### Console logs

```Shell
。
```

### Additional information

Could you give me some advice ,thank u

**Comment by hzwyjxy** [comment] 2023-02-17 04:16
If I use rocm on linux , is 'rocm 5.4.3' right?

**Comment by ClashSAN** [comment] 2023-02-17 09:57
rocm 5.1 or 5.2, but for linux it should be an automatic installation. on wiki, continue reading there.

**Comment by lshqqytiger** [comment] 2023-02-17 17:52
This is weird. When you tried to generate bigger resolution, did it fails with out of memory error? (`RuntimeError: failed to allocate ... bytes of tensor`)

**Comment by CoreSpectre** [comment] 2023-02-17 19:23
@hzwyjxy Are you using the directml versions of the repositories for _stable-diffusion-stability-ai_ and _k-diffusion_? I saw the same issue when I first installed and tried using the same branches that the main A1111 branch uses. If that's the problem, you'll need to clone these repos:

https://github.com/lshqqytiger/stablediffusion-directml.git
https://github.com/lshqqytiger/k-diffusion-directml

**Comment by Lucasnovitch** [comment] 2023-02-17 22:38
Hi everyone, I have the same error than him except that the graphic card is a RX6700XT (12 GBVram).

@hzwyjxy will confirm but here is the error : 
`RuntimeError: Could not allocate tensor with 39321760 bytes. There is not enough GPU video memory available!`

@lshqqytiger so yes the error is from the out of memory error.

@CoreSpectre For my case, yes I have these 2 repos.

**Comment by lshqqytiger** [comment] 2023-02-18 02:45
What commandline arguments did you use?

**Comment by ws132** [comment] 2023-02-18 11:01
try Launching Web UI with arguments: --no-half --precision full --opt-sub-quad-attention,
My 6900xt works fine.

**Comment by Lucasnovitch** [comment] 2023-02-18 13:09
> What commandline arguments did you use?

I used all the arguments but alone. It seems to work with all the args --no-half --precision full --opt-sub-quad-attention, for me with my 6700XT.

I can't create 1024*1024 pictures but now I can do 768*768. 

Mmmmmh with the RX6700XT (12GB) it's not possible do do 1024*1024 ??

The bug is solved for me but do not close this case, the original problem is from @hzwyjxy .

Thanks !

**Comment by lshqqytiger** [comment] 2023-02-18 13:21
DirectML developers are working on memory optimizations.
It may be possible to generate such a bigger resolution later.

**Comment by Lucasnovitch** [comment] 2023-02-18 13:22
> DirectML developers are working on memory optimizations. It may be possible to generate such a bigger resolution later.

Oh okay ^^

THank you for the information

**Comment by mengdalida** [comment] 2023-02-22 11:06
> DirectML developers are working on memory optimizations. It may be possible to generate such a bigger resolution later.

I have met the same problem, vram is almost full

**Comment by McSeaw** [comment] 2023-02-27 11:16
I met the same problem too. At 512*512 it just used no more than 7GB GPU Memory, but when I just change the size to 768*512, I found that the consumption of GPU Memory was increasing with progress until it reached the limit of 16GB. And then it crushed :(

**Comment by billxc** [comment] 2023-03-04 00:46
My Arc A770(16G) has this problem too. Just cannot draw a picture of 600*600
after adding `--no-half --precision full --opt-sub-quad-attention`, the problem is gone.
Just don't know what is the magic behind the options.

**Comment by mr-september** [comment] 2023-03-04 05:46
RX 5700 here, 8GB VRAM.
Trying to do 1080 errors out:

```
RuntimeError: Could not allocate tensor with 597196800 bytes. There is not enough GPU video memory available!
```

A quick google shows that translates to ~0.597 GB, which is far below my GPU's capacity.

Also, at the default 512x512 size, the webui maxes out both GPU and VRAM utilization just fine.

My launch options:
```
--opt-sub-quad-attention --medvram --disable-nan-check --precision full --no-half --autolaunch
```

**Comment by eximaArt** [comment] 2023-03-10 17:44
same here with a 7900XT (20gb VRAM). with "--no-half --precision full --opt-sub-quad-attention" its working for now but VRAM is still full all the time.

**Comment by cmlibo** [comment] 2023-03-17 04:27
7900xt，超过512*512就会报错，显存一直是满的，在Ubuntu中，7900xt无法正常使用stable-diffusion-webui，也无法玩游戏，还不如6600xt。在AI领域，AI不加大投入搞生态，靠游戏用户那点销量，迟早会玩完。

**Comment by lshqqytiger** [comment] 2023-03-17 05:04
Hardware level of RX 7900 XT is very enough to generate 512x512 image (despite of poor optimization of DirectML).
It is very strange that RX 7900 XT can't generate it.

**Comment by McSeaw** [comment] 2023-03-17 10:16
> 7900xt，超过512*512就会报错，显存一直是满的，在Ubuntu中，7900xt无法正常使用stable-diffusion-webui，也无法玩游戏，还不如6600xt。在AI领域，AI不加大投入搞生态，靠游戏用户那点销量，迟早会玩完。

That's because 7000 series GPU does not support ROCm now. Maybe you can use 7900xt in the upcoming ROCm5.5 .

**Comment by lshqqytiger** [comment] 2023-03-19 05:06
You can try this option, `SAFETENSORS_FAST_GPU`. https://github.com/lshqqytiger/stable-diffusion-webui-directml/discussions/17#discussioncomment-5351936
There was no difference in speed or memory occupancy on the RX 5700 XT, but it seems to work on the RX 7900 XT/X.

**Comment by lshqqytiger** [comment] 2024-04-17 17:36
Closing because this is not something I can fix.

**Closed** 2024-04-17 17:35 UTC
Labels: bug
